/* Generated By:JavaCC: Do not edit this line. CqlParserConstants.java */
package xxl.core.relational.parser;

public interface CqlParserConstants {

  int EOF = 0;
  int K_ALL = 5;
  int K_AND = 6;
  int K_ANY = 7;
  int K_AS = 8;
  int K_ASC = 9;
  int K_AVG = 10;
  int K_BETWEEN = 11;
  int K_BINARY_INTEGER = 12;
  int K_BOOLEAN = 13;
  int K_BY = 14;
  int K_CASE = 15;
  int K_CHAR = 16;
  int K_COMMENT = 17;
  int K_COMMIT = 18;
  int K_CONNECT = 19;
  int K_COUNT = 20;
  int K_CROSS = 21;
  int K_DATE = 22;
  int K_DAY = 23;
  int K_DAYS = 24;
  int K_DELETE = 25;
  int K_DESC = 26;
  int K_DISTINCT = 27;
  int K_DSTREAM = 28;
  int K_ELSE = 29;
  int K_END = 30;
  int K_EXCEPT = 31;
  int K_EXCLUSIVE = 32;
  int K_EXISTS = 33;
  int K_EXIT = 34;
  int K_FLOAT = 35;
  int K_FOR = 36;
  int K_FROM = 37;
  int K_FULL = 38;
  int K_GROUP = 39;
  int K_HOUR = 40;
  int K_HOURS = 41;
  int K_HAVING = 42;
  int K_IN = 43;
  int K_INNER = 44;
  int K_INSERT = 45;
  int K_INTEGER = 46;
  int K_INTERSECT = 47;
  int K_INTO = 48;
  int K_IS = 49;
  int K_ISTREAM = 50;
  int K_JOIN = 51;
  int K_LEFT = 52;
  int K_LIKE = 53;
  int K_LOCK = 54;
  int K_MAX = 55;
  int K_MIN = 56;
  int K_MINUTE = 57;
  int K_MINUTES = 58;
  int K_MINUS = 59;
  int K_MODE = 60;
  int K_NATURAL = 61;
  int K_NOT = 62;
  int K_NOW = 63;
  int K_NOWAIT = 64;
  int K_NULL = 65;
  int K_NUMBER = 66;
  int K_OF = 67;
  int K_ON = 68;
  int K_ONLY = 69;
  int K_OR = 70;
  int K_ORDER = 71;
  int K_OUTER = 72;
  int K_PARTITION = 73;
  int K_PRIOR = 74;
  int K_QUIT = 75;
  int K_RANGE = 76;
  int K_READ = 77;
  int K_REAL = 78;
  int K_RELATION = 79;
  int K_RIGHT = 80;
  int K_ROLLBACK = 81;
  int K_ROW = 82;
  int K_ROWS = 83;
  int K_RSTREAM = 84;
  int K_SECOND = 85;
  int K_SECONDS = 86;
  int K_SELECT = 87;
  int K_SET = 88;
  int K_SHARE = 89;
  int K_SMALLINT = 90;
  int K_START = 91;
  int K_STDDEV_POP = 92;
  int K_STDDEV_SAMP = 93;
  int K_STREAM = 94;
  int K_SUM = 95;
  int K_TABLE = 96;
  int K_THEN = 97;
  int K_TRANSACTION = 98;
  int K_UNBOUNDED = 99;
  int K_UNION = 100;
  int K_UPDATE = 101;
  int K_USING = 102;
  int K_VALUES = 103;
  int K_VARCHAR2 = 104;
  int K_VARCHAR = 105;
  int K_VAR_POP = 106;
  int K_VAR_SAMP = 107;
  int K_WHEN = 108;
  int K_WHERE = 109;
  int K_WITH = 110;
  int K_WORK = 111;
  int K_WRITE = 112;
  int S_NUMBER = 113;
  int FLOAT = 114;
  int INTEGER = 115;
  int DIGIT = 116;
  int LINE_COMMENT = 117;
  int MULTI_LINE_COMMENT = 118;
  int S_IDENTIFIER = 119;
  int LETTER = 120;
  int SPECIAL_CHARS = 121;
  int S_BIND = 122;
  int S_CHAR_LITERAL = 123;
  int S_QUOTED_IDENTIFIER = 124;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"ALL\"",
    "\"AND\"",
    "\"ANY\"",
    "\"AS\"",
    "\"ASC\"",
    "\"AVG\"",
    "\"BETWEEN\"",
    "\"BINARY_INTEGER\"",
    "\"BOOLEAN\"",
    "\"BY\"",
    "\"CASE\"",
    "\"CHAR\"",
    "\"COMMENT\"",
    "\"COMMIT\"",
    "\"CONNECT\"",
    "\"COUNT\"",
    "\"CROSS\"",
    "\"DATE\"",
    "\"DAY\"",
    "\"DAYS\"",
    "\"DELETE\"",
    "\"DESC\"",
    "\"DISTINCT\"",
    "\"DSTREAM\"",
    "\"ELSE\"",
    "\"END\"",
    "\"EXCEPT\"",
    "\"EXCLUSIVE\"",
    "\"EXISTS\"",
    "\"EXIT\"",
    "\"FLOAT\"",
    "\"FOR\"",
    "\"FROM\"",
    "\"FULL\"",
    "\"GROUP\"",
    "\"HOUR\"",
    "\"HOURS\"",
    "\"HAVING\"",
    "\"IN\"",
    "\"INNER\"",
    "\"INSERT\"",
    "\"INTEGER\"",
    "\"INTERSECT\"",
    "\"INTO\"",
    "\"IS\"",
    "\"ISTREAM\"",
    "\"JOIN\"",
    "\"LEFT\"",
    "\"LIKE\"",
    "\"LOCK\"",
    "\"MAX\"",
    "\"MIN\"",
    "\"MINUTE\"",
    "\"MINUTES\"",
    "\"MINUS\"",
    "\"MODE\"",
    "\"NATURAL\"",
    "\"NOT\"",
    "\"NOW\"",
    "\"NOWAIT\"",
    "\"NULL\"",
    "\"NUMBER\"",
    "\"OF\"",
    "\"ON\"",
    "\"ONLY\"",
    "\"OR\"",
    "\"ORDER\"",
    "\"OUTER\"",
    "\"PARTITION\"",
    "\"PRIOR\"",
    "\"QUIT\"",
    "\"RANGE\"",
    "\"READ\"",
    "\"REAL\"",
    "\"RELATION\"",
    "\"RIGHT\"",
    "\"ROLLBACK\"",
    "\"ROW\"",
    "\"ROWS\"",
    "\"RSTREAM\"",
    "\"SECOND\"",
    "\"SECONDS\"",
    "\"SELECT\"",
    "\"SET\"",
    "\"SHARE\"",
    "\"SMALLINT\"",
    "\"START\"",
    "\"STDDEV_POP\"",
    "\"STDDEV_SAMP\"",
    "\"STREAM\"",
    "\"SUM\"",
    "\"TABLE\"",
    "\"THEN\"",
    "\"TRANSACTION\"",
    "\"UNBOUNDED\"",
    "\"UNION\"",
    "\"UPDATE\"",
    "\"USING\"",
    "\"VALUES\"",
    "\"VARCHAR2\"",
    "\"VARCHAR\"",
    "\"VAR_POP\"",
    "\"VAR_SAMP\"",
    "\"WHEN\"",
    "\"WHERE\"",
    "\"WITH\"",
    "\"WORK\"",
    "\"WRITE\"",
    "<S_NUMBER>",
    "<FLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<S_BIND>",
    "<S_CHAR_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\";\"",
    "\"=\"",
    "\".\"",
    "\"!=\"",
    "\"#\"",
    "\"<>\"",
    "\">\"",
    "\">=\"",
    "\"<\"",
    "\"<=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\".*\"",
    "\"[\"",
    "\"]\"",
    "\"?\"",
    "\"||\"",
    "\"/\"",
    "\"**\"",
    "\" AVG\"",
  };

}
